### ISSUE TITLE
(AsmResolver) CilVirtualMachine to use MemoryLayoutAttributes instead of Is32Bit

### ISSUE THREAD

**Issue by JPaja** [Washi1337/Echo#104]
This could be useful in cases when emulator is used for static analysis and we dont know exact platform or we want to have result for boath

This would disable Pointer emulation, or limit it to 32 bit arithmetic and if it overflows / underflows than it changes it to Unknown
since we dont know how to deal with it

Also in cases of platform dependent types it should push unknown values in cases of sizeof or pointer manipulations

Related:
https://github.com/Washi1337/AsmResolver/issues/143

**Comment by Washi1337** [comment]
This has quite a few fundamental problems.

First, from an architectural standpoint, `Is32Bit` is a property defined in `IPointerValue` and `ObjectReference`, which are defined in `Echo.Concrete`. Replacing this with a `MemoryLayoutAttributes` property in these types would therefore mean `Echo.Core` will start to depend on `AsmResolver.DotNet` which goes against the design principles of Echo (one modular base for every platform). There is the possibility that we _copy_ the `MemoryLayoutAttributes` type from AsmResolver into `Echo.Concrete`, however I foresee that this easily requires immense refactoring though.

But perhaps the biggest problem with this, is that the entire CIL VM API is completely based around the type memory layout mechanisms of AsmResolver. If we allow the VM to be put in "platform agnostic" mode, then we cannot use this type memory layout anymore as a ground truth. This would not only result in pointer emulation being disabled, but basically any form of LLE for objects, structs, and arrays. If a type is platform dependent, then the entire layout of the value can change depending on whether it was loaded in a 32-bit or 64-bit environment. Even basic operations like the arithmetic operations you mention would have to be revised and most likely increase in complexity and decrease in efficiency. 

We cannot store both representations either per `IConcreteValue`, as this would result in a massive memory consumption increase and degradation in efficiency. For objects it would technically be possible to move everything to HLE, but this is not only less accurate emulation, but slower as well. Furthermore, using unknowns for all these kinds of values can easily make most values that live in the sandbox marked completely unknown, which makes me question the usability of the emulator to begin with at that point.

What exactly are you trying to do? If you want to have the result of both, why not just run it twice? Because as it is right now, I have my doubts about whether it is worth the refactor.

**Comment by JPaja** [comment]
> t store both representations either per `IConcreteValue`, as this would result in a massive memory consumption increase and degradation in efficiency. For objects it would technically be possible to move everything to HLE, but this is not only less accurate emulation, but slower as well. Furthermore, using unknowns for all these kinds of values can easily make most values that live in the sandbox marked completely unknown, which makes me question the usability of the emulator to begin with at that point.
> 
> What exactly are you trying to do? If you want to have the result of both, why not just run it twice? Because as it is right now, I have my doubts about whether it is worth the refactor.

Well it is true that this can be achived with running boath 64 and 32 but its not nice solution in my opitnion.
Regarding the usage, it can be used in deobfsucation and optimization of method bodies, for example
just simplifying mutations and replacing sizeof instructions, and inlining in general. 
When certain code like sizeof on struct with IntPtr value inside when emulated would yield 2 different results so that would mean shouldnt inline such case.

Beauty of emulation is you can just run emulation and parse value at the end, and if value is not uknown we are certain the value is 'constnat' and we can inlinie it. But somewhere deep inside whole expression could be hiding platform dependent code which would mean we cannot just "get the value" and we would have to check whole passed expression if it was platform dependent

**Comment by Washi1337** [comment]
Superseded by the new implementation of the CIL VM (See #120)
